### ISSUE TITLE
Removed option from "Selection" type is visible

### ISSUE THREAD

**Issue by pawlosck** [stefan-niedermann/nextcloud-tables#17]
The same case - https://github.com/stefan-niedermann/nextcloud-tables/issues/16

1. Remove last option from "Selection" type
2. Add the same option (with the same value)
3. Open Android app and go to table.
4. Touch button "Add row"
5. Removed and new option is visible. In web app, removed option is not visible

**Comment by stefan-niedermann** [comment]
Thank you for the report!

This issue should be fixed in `1.1.1` - Please reopen in case it occurs with this or a later version.

**Comment by pawlosck** [comment]
Not fixed. Today, I installed latest version from fdroid (1.1.2).
I opened the same table with one row and removed option is still visible.

**Comment by stefan-niedermann** [comment]
Are you still able to reproduce the issue in `2.0.2`?

**Comment by stefan-niedermann** [comment]
Closing due to missing feedback - However, please feel free to reopen in case the issue persists in `2.0.2` or newer versions.
